apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudpredict-config
  namespace: cloudpredict
  labels:
    app: cloudpredict
data:
  component: api
  FLASK_ENV: "production"
  FLASK_APP: "app.py"
  MODEL_PATH: "/app/ml/models/model.joblib"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "cloudpredict"
  POSTGRES_USER: "cloudpredict"
  LOG_LEVEL: "INFO"
